version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

install:
  - git submodule update --init --recursive

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -H. -BBuild -A%PLATFORM%

# build with MSBuild
build:
  project: Build\CPPTemplate.sln
  parallel: true
  verbosity: normal

test_script:
  - cd Build
  - ctest -V -C %CONFIGURATION%
